#ifndef HTTPSTATUSCODE_HPP
# define HTTPSTATUSCODE_HPP

enum HttpStatusCode
{
	OK = 200,
	BAD_REQUEST = 400,
	NOT_FOUND = 404,
	LENGTH_REQUIRED = 411,
	PAYLOAD_TOO_LARGE = 413,
	URI_TOO_LONG  = 414,
	NOT_IMPLEMENTED = 501,
	VERSION_NOT_SUPPORTED = 505
};

#endif