server {
    listen 127.0.0.1:8080;
    root ./www/site-a;
    index index.html;
    error_page 404 /errors/404.html;

    location / {
        allowed_methods GET;
        autoindex off;
    }

    location /docs {
        root ./www/documents;
        index index.html;
        allowed_methods GET;
        autoindex on;
    }

    location /old {
        allowed_methods GET;
        return 301 /docs/;
    }

    location /upload {
        allowed_methods POST;
        upload_path ./www/uploads;
        client_max_body_size 1M;
    }

    location /files {
        root ./www/uploads;
        allowed_methods GET DELETE;
        autoindex on;
    }

    location /cgi-bin {
        root ./www/cgi-bin;
        allowed_methods GET POST;
        cgi .py /usr/bin/python3;
    }
}

server {
    listen 127.0.0.2:8081;
    root ./www/site-b;
    index index.html;

    location / {
        allowed_methods GET;
        autoindex off;
    }
}