server {
    listen 8080;
    server_name localhost;

    root ./www;
    index index.html index.htm;

    client_max_body_size 10M;

    error_page 404 /404_server.html;

    location / {
        allowed_methods GET POST;
        autoindex off;
    }

    location /test_autoindex {
        root ./www/test_autoindex;
        autoindex on;
    }

    location /images {
        root /var/www/assets;
        allowed_methods GET;
        autoindex on;
    }

    location /upload {
        allowed_methods POST;
        upload_path ./www/uploads;
    }

    location /files {
        root ./www/uploads;
        allowed_methods GET DELETE;
        autoindex on;
    }

    location /cgi-bin {
        root ./www/cgi-bin;
        index echo.py;
        allowed_methods GET POST;
        cgi .py /usr/bin/python3;
    }
    location /old {
        return 301 /;
    }
}
